export const USER_CONNECTED = "USER_CONNECTED";
export const FRIEND_REQUEST = "FRIEND_REQUEST";
export const CANCEL_FRIEND_REQUEST = "CANCEL_FRIEND_REQUEST";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const DECLINE_FRIEND_REQUEST = "DECLINE_FRIEND_REQUEST";
