export const GET_TOTAL_SQUADS_FOR_EVENT = "GET_TOTAL_SQUADS_FOR_EVENT";
export const GET_TOTAL_SQUADS = "GET_TOTAL_SQUADS";
export const GET_TOTAL_DUO = "GET_TOTAL_DUO";
export const GET_TOTAL_SOLO = "GET_TOTAL_SOLO";
