export const GET_TOURNAMENT_DATA_REQUEST = "GET_TOURNAMENT_DATA_REQUEST";
export const GET_TOURNAMENT_DATA_SUCCESS = "GET_TOURNAMENT_DATA_SUCCESS";
export const GET_TOURNAMENT_DATA_FAIL = "GET_TOURNAMENT_DATA_FAIL";

export const TOURNAMENT_REGISTER_REQUEST = "TOURNAMENT_REGISTER_REQUEST";
export const TOURNAMENT_REGISTER_SUCCESS = "TOURNAMENT_REGISTER_SUCCESS";
export const TOURNAMENT_REGISTER_FAIL = "TOURNAMENT_REGISTER_FAIL";
export const TOURNAMENT_REGISTER_CANCEL = "TOURNAMENT_REGISTER_CANCEL";

export const GET_DATA = "GET_DATA";
export const GET_TABLE_HEADER_DATA = "GET_TABLE_HEADER_DATA";
export const SORT_COLUMN = "SORT_COLUMN";

export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";
