export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_VERIFY_REQUEST = "USER_VERIFY_REQUEST";
export const USER_VERIFY_SUCCESS = "USER_VERIFY_SUCCESS";
export const USER_VERIFY_FAIL = "USER_VERIFY_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_FRIEND_INVOKE_REQUEST = "USER_FRIEND_INVOKE_REQUEST";
export const USER_FRIEND_INVOKE_SUCCESS = "USER_FRIEND_INVOKE_SUCCESS";
export const USER_FRIEND_INVOKE_FAIL = "USER_FRIEND_INVOKE_FAIL";

export const USER_FRIEND_CANCEL_REQUEST = "USER_FRIEND_CANCEL_REQUEST";
export const USER_FRIEND_CANCEL_SUCCESS = "USER_FRIEND_CANCEL_SUCCESS";
export const USER_FRIEND_CANCEL_FAIL = "USER_FRIEND_CANCEL_FAIL";

export const ACCEPT_FRIEND_REQUEST_SUCCESS = "ACCEPT_FRIEND_REQUEST_SUCCESS";
export const ACCEPT_FRIEND_REQUEST_FAILED = "ACCEPT_FRIEND_REQUEST_FAILED";

export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAILED = "REMOVE_FRIEND_FAILED";

export const FRIENDS_LOAD_SUCCESS = "FRIENDS_LOAD_SUCCESS";
export const FRIEND_ADD_SUCCESS = "FRIEND_ADD_SUCCESS";
